name: "Label Merge Conflicts"
on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '0 * * * *' # Every hour

jobs:
  triage:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
