name: "conflict-finder"
on: 
  push:
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: hcancelik/pr-conflict-finder@v1
        with:
          secret_token: ${{ secrets.GITHUB_TOKEN }}
          conflict_label: "Has Conflict"
          max_tries: 5
          wait_ms: 5000
