name: Auto Resolve Merge Conflicts with AI

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to resolve'
        required: false
        type: number

  schedule:
    - cron: '0 * * * *'

jobs:
  auto-resolve-conflicts:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -e .

      - name: Debug Info
        run: |
          echo "Manual PR input: ${{ inputs.pr_number }}"

      - name: Run resolver
        run: python resolve_conflicts/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PR_NUMBER: ${{ inputs.pr_number }}
