name: Auto Resolve Merge Conflicts with AI

on:
  pull_request:
    types: [ labeled ]

  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to resolve'
        required: false
        type: number

jobs:
  auto-resolve-conflicts:
    if: ${{ github.event.label.name == 'stitch fix conflicts' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -e .

      - name: Determine PR Number
        id: get-pr
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "pr=${{ github.event.inputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "pr=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Run AI Conflict Resolver
        run: python resolve_conflicts/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PR_NUMBER: ${{ steps.get-pr.outputs.pr }}
