name: Auto Resolve Merge Conflicts with AI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-resolve-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run resolver
        uses: ./  # This references action.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
