name: Fix Merge Conflicts with AI

on:
  push:                      # Trigger on every push
  schedule:                  # Trigger every 4 hours (UTC)
    - cron: '0 */4 * * *'
  workflow_dispatch:         # Manual trigger via GitHub Actions UI

jobs:
  merge_conflict_job:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    steps:
      - uses: actions/checkout@v2
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0
