name: Auto Resolve Merge Conflicts with AI

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-resolve-conflicts:
    if: github.event.label.name == 'stitch fix conflicts'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -e .

      - name: Debug Info
        run: |
          echo "Running for PR #${{ github.event.pull_request.number }}"

      - name: Run AI Conflict Resolver
        run: python resolve_conflicts/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
