name: Auto Resolve Merge Conflicts with AI

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to resolve'
        required: false
        type: number

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-resolve-conflicts:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.issue.pull_request && startsWith(github.event.comment.body, '/stitch-fix'))

    runs-on: ubuntu-latest

    steps:
      - name: Extract PR number and branch
        id: pr-info
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "PR_NUMBER=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
          else
            echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          fi

          echo "📦 Fetching PR metadata for PR #$PR_NUMBER"

          pr_data=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github+json" \
                          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")

          head_ref=$(echo "$pr_data" | jq -r .head.ref)
          base_ref=$(echo "$pr_data" | jq -r .base.ref)

          echo "HEAD_REF=$head_ref" >> $GITHUB_ENV
          echo "BASE_REF=$base_ref" >> $GITHUB_ENV
          echo "✅ Found head ref: $head_ref"
        env:
          PR_NUMBER: ""

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.HEAD_REF }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -e .

      - name: Run AI Conflict Resolver
        run: python resolve_conflicts/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
